export const FETCH_APROVACAO: string = "FETCH_APROVACAO";
export const FETCH_APROVACAO_RESET: string = "FETCH_APROVACAO_RESET";
export const FETCH_DOCUMENTO: string = "FETCH_DOCUMENTO";
export const FETCH_DOCUMENTO_MODAL: string = "FETCH_DOCUMENTO_MODAL";
export const FETCH_DOCUMENTO_CONFIRMACAO: string =
	"FETCH_DOCUMENTO_CONFIRMACAO";
export const SET_APROVACAO_FILTER_TYPE: string = "SET_APROVACAO_FILTER_TYPE";
